# These are supported funding model platforms

github: [alroniks]
patreon: ivanklimchuk
custom: ["https://yoomoney.ru/to/41001878021446/1100", yoomoney.ru]
custom: ["https://www.buymeacoffee.com/alroniks", buymeacoffee.com]
