baseURL = "https://pravilna.by"

title = "Правільна!"
description = "desc"

DefaultContentLanguage = "be"
languageCode = "be-BY"

publishDir = "docs"
theme="rules"

disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

googleAnalytics = "UA-127301756-1"

[[menu.main]]
    name = "Усе правілы"
    weight = 1
    url = "/rules/"

[[menu.main]]
    name = "Падтрымаць праект"
    weight = 2
    url = "support"